### ISSUE TITLE
can you give a litter example for how to use it

### ISSUE THREAD

**Issue by wsdjeg** [fdinoff/neovim-java-client#6]
now i am using vim and maven to create my own android project ,use Javacomplete2 ycm for code completion

**Comment by fdinoff** [comment]
Sorry, Didn't see this. 

What are you trying to do? It doesn't sound like you are trying to write a plugin for neovim. The point of the library is to interface with neovim over the msgpack api.

**Comment by wsdjeg** [comment]
i am not good at coding, i just use the plugin,now i am using javacomplete2,and it works well,i have try with neovim ,it has a lot of bugs,and when it update,it do not care about the old configretion.as you know ,not long ago,neovim change it's .nvimrc to ~/.config/nvim/init.vim,many people do not know this ,and open many issues.i think the best way it support both ~/.nvimrc and  ~/.config/nvim/init.vim at the first update.nest version remove the support of ~/.nvimrc

**Comment by fdinoff** [comment]
Javacomplete2 does something completely different from this plugin. It sounds like you want an autocompletion plugin that works with neovim. neovim-java-client is not that (I'm not even sure I would say it is usable)

You might have better luck asking on neovim's gitter/irc channel.

**Comment by wsdjeg** [comment]
thank you
